using System.Net;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using AdminPanelAPI.Models;

namespace AdminPanelAPI.Services
{
    /// <summary>
    /// Fetches track enrichment on demand and caches it. Sources, all free and
    /// keyed off the ISRC / artist+title we already store:
    ///   - MusicBrainz: writers, composers, producers (with artist MBIDs so a
    ///     future "more tracks by this person" link can resolve by id), album,
    ///     release date, label.
    ///   - Wikipedia: a short human-readable description.
    ///   - Spotify: album, release date, 30s preview (reusing the existing
    ///     client-credentials token).
    /// </summary>
    public class TrackDetailsService : ITrackDetailsService
    {
        private readonly IMusicIdentificationJobRepository _repository;
        private readonly HttpClient _http;
        private readonly IConfiguration _configuration;
        private readonly ILogger<TrackDetailsService> _logger;

        private string? _accessToken;
        private DateTimeOffset _tokenExpiry = DateTimeOffset.MinValue;

        // Web-search-capable model used for film-specific descriptions.
        private const string AiModel = "gpt-4o-mini";

        // Generic album words that don't distinguish one soundtrack from
        // another, so they shouldn't count as track/album context.
        private static readonly HashSet<string> AlbumFiller = new(StringComparer.Ordinal)
        {
            "original", "motion", "picture", "soundtrack", "score", "music",
            "from", "the", "of", "and", "a", "an", "ost", "deluxe", "edition",
            "expanded", "complete", "volume", "vol"
        };

        public TrackDetailsService(
            IMusicIdentificationJobRepository repository,
            HttpClient http,
            IConfiguration configuration,
            ILogger<TrackDetailsService> logger)
        {
            _repository = repository;
            _http = http;
            _configuration = configuration;
            _logger = logger;
            // MusicBrainz requires a descriptive, contactable User-Agent.
            if (!_http.DefaultRequestHeaders.Contains("User-Agent"))
                _http.DefaultRequestHeaders.Add("User-Agent", "shotdeck-music/1.0 (track-details)");
        }

        public async Task<TrackDetails?> GetOrFetchAsync(long songId, int? movieId, bool refresh, CancellationToken cancellationToken)
        {
            var song = await _repository.GetSongForDetailsAsync(songId, cancellationToken);
            if (song == null) return null;

            // Song-level metadata (credits, album, links) is cached in
            // track_details and reused across every movie that shares the song.
            TrackDetails details;
            var cached = refresh ? null : await _repository.GetTrackDetailsAsync(songId, cancellationToken);
            if (cached != null)
            {
                details = cached;
                details.Title = song.Title;
                details.Artist = song.Artist;
                details.SpotifyUrl = song.SpotifyUrl;
            }
            else
            {
                details = new TrackDetails
                {
                    SongId = songId,
                    Title = song.Title,
                    Artist = song.Artist,
                    SpotifyUrl = song.SpotifyUrl
                };

                await EnrichFromMusicBrainzAsync(details, song, cancellationToken);
                await EnrichFromWikipediaAsync(details, song, cancellationToken);
                await EnrichFromSpotifyAsync(details, song, cancellationToken);

                await _repository.UpsertTrackDetailsAsync(details, cancellationToken);
            }

            // A richer, film-specific write-up (how the track is used in this
            // movie) is generated by the LLM and cached per (song, movie). It
            // overrides the song-level Wikipedia blurb when available.
            if (movieId.HasValue)
                await ApplyAiDescriptionAsync(details, movieId.Value, refresh, cancellationToken);

            return details;
        }

        // ---- MusicBrainz -----------------------------------------------------

        private async Task EnrichFromMusicBrainzAsync(TrackDetails details, MovieSongRow song, CancellationToken cancellationToken)
        {
            try
            {
                var recordingId = await ResolveRecordingIdAsync(song, cancellationToken);
                if (recordingId == null) return;

                details.MusicbrainzUrl = "https://musicbrainz.org/recording/" + recordingId;

                var json = await GetStringAsync(
                    $"https://musicbrainz.org/ws/2/recording/{recordingId}?inc=artist-rels+work-rels+releases&fmt=json",
                    cancellationToken);
                if (json == null) return;

                using var doc = JsonDocument.Parse(json);
                var root = doc.RootElement;

                // Producers/engineers are artist-relations on the recording.
                string? workId = null;
                if (root.TryGetProperty("relations", out var rels) && rels.ValueKind == JsonValueKind.Array)
                {
                    foreach (var rel in rels.EnumerateArray())
                    {
                        var type = rel.TryGetProperty("type", out var t) ? t.GetString() : null;
                        if (type == "producer" && rel.TryGetProperty("artist", out var pa))
                            AddCredit(details.Producers, pa);
                        else if (type == "performance" && workId == null && rel.TryGetProperty("work", out var w)
                                 && w.TryGetProperty("id", out var wid))
                            workId = wid.GetString();
                    }
                }

                // Album + release date + label from the first release.
                if (root.TryGetProperty("releases", out var releases) &&
                    releases.ValueKind == JsonValueKind.Array && releases.GetArrayLength() > 0)
                {
                    var rel = releases[0];
                    if (string.IsNullOrWhiteSpace(details.Album) && rel.TryGetProperty("title", out var rt))
                        details.Album = rt.GetString();
                    if (string.IsNullOrWhiteSpace(details.ReleaseDate) && rel.TryGetProperty("date", out var rd))
                        details.ReleaseDate = rd.GetString();
                }

                // Writers/composers live on the work behind the recording.
                if (workId != null)
                    await EnrichFromWorkAsync(details, workId, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogDebug(ex, "MusicBrainz enrichment failed for song {SongId}", details.SongId);
            }
        }

        private async Task<string?> ResolveRecordingIdAsync(MovieSongRow song, CancellationToken cancellationToken)
        {
            if (!string.IsNullOrWhiteSpace(song.Isrc))
            {
                var json = await GetStringAsync(
                    $"https://musicbrainz.org/ws/2/isrc/{Uri.EscapeDataString(song.Isrc)}?inc=recordings&fmt=json",
                    cancellationToken);
                if (json != null)
                {
                    using var doc = JsonDocument.Parse(json);
                    if (doc.RootElement.TryGetProperty("recordings", out var recs) &&
                        recs.ValueKind == JsonValueKind.Array && recs.GetArrayLength() > 0 &&
                        recs[0].TryGetProperty("id", out var id))
                        return id.GetString();
                }
            }

            if (!string.IsNullOrWhiteSpace(song.Title))
            {
                var query = $"recording:\"{song.Title}\"";
                if (!string.IsNullOrWhiteSpace(song.Artist))
                    query += $" AND artist:\"{song.Artist}\"";
                var json = await GetStringAsync(
                    $"https://musicbrainz.org/ws/2/recording?query={Uri.EscapeDataString(query)}&fmt=json&limit=1",
                    cancellationToken);
                if (json != null)
                {
                    using var doc = JsonDocument.Parse(json);
                    if (doc.RootElement.TryGetProperty("recordings", out var recs) &&
                        recs.ValueKind == JsonValueKind.Array && recs.GetArrayLength() > 0 &&
                        recs[0].TryGetProperty("id", out var id))
                        return id.GetString();
                }
            }

            return null;
        }

        private async Task EnrichFromWorkAsync(TrackDetails details, string workId, CancellationToken cancellationToken)
        {
            var json = await GetStringAsync(
                $"https://musicbrainz.org/ws/2/work/{workId}?inc=artist-rels+label-rels&fmt=json",
                cancellationToken);
            if (json == null) return;

            using var doc = JsonDocument.Parse(json);
            if (!doc.RootElement.TryGetProperty("relations", out var rels) || rels.ValueKind != JsonValueKind.Array)
                return;

            foreach (var rel in rels.EnumerateArray())
            {
                var type = rel.TryGetProperty("type", out var t) ? t.GetString() : null;

                // Publishers are the music-publishing companies on the work,
                // credited as label relationships (not artists).
                if (type == "publishing" && rel.TryGetProperty("label", out var label))
                {
                    AddCredit(details.Publishers, label);
                    continue;
                }

                if (!rel.TryGetProperty("artist", out var artist)) continue;
                switch (type)
                {
                    case "composer":
                        AddCredit(details.Composers, artist);
                        break;
                    case "writer":
                    case "lyricist":
                    case "librettist":
                        AddCredit(details.Writers, artist);
                        break;
                    case "producer":
                        AddCredit(details.Producers, artist);
                        break;
                }
            }
        }

        private static void AddCredit(List<MusicCredit> list, JsonElement artist)
        {
            var name = artist.TryGetProperty("name", out var n) ? n.GetString() : null;
            if (string.IsNullOrWhiteSpace(name)) return;
            var mbid = artist.TryGetProperty("id", out var id) ? id.GetString() : null;
            if (list.Any(c => string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase))) return;
            list.Add(new MusicCredit { Name = name, Mbid = mbid });
        }

        // ---- Wikipedia -------------------------------------------------------

        private async Task EnrichFromWikipediaAsync(TrackDetails details, MovieSongRow song, CancellationToken cancellationToken)
        {
            if (string.IsNullOrWhiteSpace(song.Title)) return;
            try
            {
                var srsearch = song.Title + (string.IsNullOrWhiteSpace(song.Artist) ? "" : " " + song.Artist) + " song";
                var searchJson = await GetStringAsync(
                    "https://en.wikipedia.org/w/api.php?action=query&list=search&format=json&srlimit=5&srsearch="
                    + Uri.EscapeDataString(srsearch),
                    cancellationToken);
                if (searchJson == null) return;

                var pageTitles = new List<string>();
                using (var sdoc = JsonDocument.Parse(searchJson))
                {
                    var hits = sdoc.RootElement.GetProperty("query").GetProperty("search");
                    foreach (var hit in hits.EnumerateArray())
                    {
                        var pt = hit.TryGetProperty("title", out var ptEl) ? ptEl.GetString() : null;
                        if (!string.IsNullOrWhiteSpace(pt)) pageTitles.Add(pt);
                    }
                }
                if (pageTitles.Count == 0) return;

                // The top text hit is often an unrelated article that merely
                // shares words (e.g. a generic cue title like "Blood Red"
                // matching an unrelated song). Only accept a page that is
                // clearly about this track: its title contains the track's
                // title tokens, or its summary mentions the artist.
                var titleTokens = Tokenize(song.Title);
                var artistNorm = Normalize(song.Artist);
                // Context tokens a page must touch when we only have an artist
                // match: the distinctive words of the track title + album
                // (album set by the MusicBrainz pass above), minus album filler.
                // Without this, a prolific composer (e.g. Thomas Newman) matches
                // ANY of his soundtrack pages — an American Beauty cue was
                // pulling the "Road to Perdition" score article.
                var contextTokens = new HashSet<string>(titleTokens);
                foreach (var tok in Tokenize(details.Album))
                    if (!AlbumFiller.Contains(tok)) contextTokens.Add(tok);

                foreach (var pageTitle in pageTitles)
                {
                    var summaryJson = await GetStringAsync(
                        "https://en.wikipedia.org/api/rest_v1/page/summary/"
                        + Uri.EscapeDataString(pageTitle.Replace(' ', '_')),
                        cancellationToken);
                    if (summaryJson == null) continue;

                    using var doc = JsonDocument.Parse(summaryJson);
                    var root = doc.RootElement;

                    var type = root.TryGetProperty("type", out var ty) ? ty.GetString() : null;
                    if (type == "disambiguation") continue;

                    var extract = root.TryGetProperty("extract", out var e) ? e.GetString() : null;
                    if (string.IsNullOrWhiteSpace(extract)) continue;

                    var pageTitleTokens = Tokenize(pageTitle);
                    var titleMatch = titleTokens.Count > 0 && titleTokens.All(pageTitleTokens.Contains);
                    // Artist match alone is too loose for prolific composers, so
                    // also require the page title to overlap the track/album
                    // context (e.g. "Joker" for a Joker cue).
                    var artistMatch = !string.IsNullOrEmpty(artistNorm) &&
                                      Normalize(extract).Contains(artistNorm) &&
                                      pageTitleTokens.Any(contextTokens.Contains);
                    if (!titleMatch && !artistMatch) continue;

                    details.Description = extract;
                    details.DescriptionSource = "wikipedia";
                    if (root.TryGetProperty("content_urls", out var cu) &&
                        cu.TryGetProperty("desktop", out var desk) &&
                        desk.TryGetProperty("page", out var pageUrl))
                        details.WikipediaUrl = pageUrl.GetString();
                    return;
                }
            }
            catch (Exception ex)
            {
                _logger.LogDebug(ex, "Wikipedia enrichment failed for song {SongId}", details.SongId);
            }
        }

        // ---- Spotify ---------------------------------------------------------

        private async Task EnrichFromSpotifyAsync(TrackDetails details, MovieSongRow song, CancellationToken cancellationToken)
        {
            var trackId = ExtractTrackId(song.SpotifyUrl);
            if (trackId == null) return;

            var clientId = _configuration["Spotify:ClientId"] ?? _configuration["SPOTIFY_CLIENT_ID"];
            var clientSecret = _configuration["Spotify:ClientSecret"] ?? _configuration["SPOTIFY_CLIENT_SECRET"];
            if (string.IsNullOrWhiteSpace(clientId) || string.IsNullOrWhiteSpace(clientSecret)) return;

            try
            {
                var token = await GetSpotifyTokenAsync(clientId, clientSecret, cancellationToken);
                if (token == null) return;

                using var req = new HttpRequestMessage(HttpMethod.Get, "https://api.spotify.com/v1/tracks/" + trackId);
                req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
                using var resp = await _http.SendAsync(req, cancellationToken);
                if (!resp.IsSuccessStatusCode) return;

                var body = await resp.Content.ReadAsStringAsync(cancellationToken);
                using var doc = JsonDocument.Parse(body);
                var root = doc.RootElement;

                if (root.TryGetProperty("preview_url", out var pv) && pv.ValueKind == JsonValueKind.String)
                    details.PreviewUrl = pv.GetString();

                if (root.TryGetProperty("album", out var album))
                {
                    if (album.TryGetProperty("name", out var an))
                        details.Album = an.GetString();
                    if (album.TryGetProperty("release_date", out var rd))
                        details.ReleaseDate = rd.GetString();
                }
            }
            catch (Exception ex)
            {
                _logger.LogDebug(ex, "Spotify enrichment failed for song {SongId}", details.SongId);
            }
        }

        // ---- OpenAI (film-specific description) ------------------------------

        private async Task ApplyAiDescriptionAsync(TrackDetails details, int movieId, bool refresh, CancellationToken cancellationToken)
        {
            var apiKey = _configuration["OpenAI:ApiKey"] ?? _configuration["OPENAI_API_KEY"];
            if (string.IsNullOrWhiteSpace(apiKey)) return;

            try
            {
                if (!refresh)
                {
                    var cached = await _repository.GetAiDescriptionAsync(details.SongId, movieId, cancellationToken);
                    if (cached != null && !string.IsNullOrWhiteSpace(cached.Description))
                    {
                        details.Description = CleanDescription(cached.Description);
                        details.DescriptionSource = "openai";
                        details.DescriptionSources = cached.Sources;
                        return;
                    }
                }

                var movie = await _repository.GetMovieInfoAsync(movieId, cancellationToken);
                var generated = await GenerateAiDescriptionAsync(details, movie, apiKey, cancellationToken);
                if (generated == null || string.IsNullOrWhiteSpace(generated.Description)) return;

                await _repository.UpsertAiDescriptionAsync(details.SongId, movieId, generated, AiModel, cancellationToken);
                details.Description = generated.Description;
                details.DescriptionSource = "openai";
                details.DescriptionSources = generated.Sources;
            }
            catch (Exception ex)
            {
                _logger.LogDebug(ex, "OpenAI description failed for song {SongId} movie {MovieId}", details.SongId, movieId);
            }
        }

        private async Task<AiDescription?> GenerateAiDescriptionAsync(TrackDetails details, MovieInfo? movie, string apiKey, CancellationToken cancellationToken)
        {
            var facts = new StringBuilder();
            facts.Append("Track: ").Append(details.Title ?? "(unknown)");
            if (!string.IsNullOrWhiteSpace(details.Artist)) facts.Append(" — ").Append(details.Artist);
            facts.AppendLine();
            if (!string.IsNullOrWhiteSpace(details.Album)) facts.Append("Album: ").AppendLine(details.Album);
            if (!string.IsNullOrWhiteSpace(details.ReleaseDate)) facts.Append("Released: ").AppendLine(details.ReleaseDate);
            AppendCredits(facts, "Writers", details.Writers);
            AppendCredits(facts, "Composers", details.Composers);
            AppendCredits(facts, "Producers", details.Producers);
            if (movie != null && !string.IsNullOrWhiteSpace(movie.Title))
            {
                facts.Append("Film it appears in: ").Append(movie.Title);
                if (movie.Year.HasValue) facts.Append(" (").Append(movie.Year.Value).Append(')');
                facts.AppendLine();
            }

            var prompt =
                "You are writing a short, engaging 'about this song' note for a film-music database. " +
                "Use web search to verify facts and cite sources. Cover: brief background on the song/composition " +
                "(who wrote it, when, what it's about) and, if the film is given, how the track is used in that film " +
                "and why it fits. Write 120-200 words of plain prose (no markdown, no headings, no bullet points). " +
                "Only state things you can verify; if you are unsure, leave it out rather than guessing. Do not fabricate.\n\n" +
                "Known facts (already verified, use them):\n" + facts;

            var payload = new
            {
                model = AiModel,
                tools = new[] { new { type = "web_search_preview" } },
                input = prompt
            };

            using var req = new HttpRequestMessage(HttpMethod.Post, "https://api.openai.com/v1/responses");
            req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
            req.Content = new StringContent(JsonSerializer.Serialize(payload), Encoding.UTF8, "application/json");
            using var resp = await _http.SendAsync(req, cancellationToken);
            if (!resp.IsSuccessStatusCode)
            {
                _logger.LogDebug("OpenAI responses call returned {Status}", resp.StatusCode);
                return null;
            }

            var body = await resp.Content.ReadAsStringAsync(cancellationToken);
            using var doc = JsonDocument.Parse(body);
            var root = doc.RootElement;

            var text = new StringBuilder();
            var sources = new List<LinkRef>();
            var seenUrls = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            if (root.TryGetProperty("output", out var output) && output.ValueKind == JsonValueKind.Array)
            {
                foreach (var item in output.EnumerateArray())
                {
                    if (!item.TryGetProperty("type", out var it) || it.GetString() != "message") continue;
                    if (!item.TryGetProperty("content", out var content) || content.ValueKind != JsonValueKind.Array) continue;

                    foreach (var c in content.EnumerateArray())
                    {
                        if (!c.TryGetProperty("type", out var ct) || ct.GetString() != "output_text") continue;
                        if (c.TryGetProperty("text", out var tx) && tx.ValueKind == JsonValueKind.String)
                            text.Append(tx.GetString());

                        if (!c.TryGetProperty("annotations", out var anns) || anns.ValueKind != JsonValueKind.Array) continue;
                        foreach (var ann in anns.EnumerateArray())
                        {
                            if (!ann.TryGetProperty("type", out var at) || at.GetString() != "url_citation") continue;
                            var url = ann.TryGetProperty("url", out var u) ? u.GetString() : null;
                            if (string.IsNullOrWhiteSpace(url) || !seenUrls.Add(url)) continue;
                            var title = ann.TryGetProperty("title", out var ti) ? ti.GetString() : null;
                            sources.Add(new LinkRef { Title = title, Url = url });
                        }
                    }
                }
            }

            var final = CleanDescription(text.ToString());
            return string.IsNullOrEmpty(final) ? null : new AiDescription { Description = final, Sources = sources };
        }

        private static void AppendCredits(StringBuilder sb, string label, List<MusicCredit> credits)
        {
            if (credits.Count == 0) return;
            sb.Append(label).Append(": ").AppendLine(string.Join(", ", credits.Select(c => c.Name)));
        }

        // The model tends to leave inline markdown citations like
        // "([en.wikipedia.org](https://...))" and emphasis markers (*text*,
        // **text**) in the prose. Sources are shown separately, so strip both
        // to keep the displayed text clean.
        private static string CleanDescription(string? text)
        {
            if (string.IsNullOrWhiteSpace(text)) return "";
            var s = text;
            // Inline markdown link, optionally wrapped in parentheses:
            //   ([label](url))  or  [label](url)
            s = Regex.Replace(s, @"\s*\(?\[[^\]]*\]\((?:https?:)?[^)]*\)\)?", "");
            // Bold/italic emphasis markers around words.
            s = Regex.Replace(s, @"(\*{1,3}|_{1,3})(?=\S)(.+?)(?<=\S)\1", "$2");
            // Collapse any doubled spaces left behind and tidy space-before-punct.
            s = Regex.Replace(s, @"[ \t]{2,}", " ");
            s = Regex.Replace(s, @" +([.,;:!?])", "$1");
            return s.Trim();
        }

        private async Task<string?> GetSpotifyTokenAsync(string clientId, string clientSecret, CancellationToken cancellationToken)
        {
            if (_accessToken != null && DateTimeOffset.UtcNow < _tokenExpiry)
                return _accessToken;

            using var req = new HttpRequestMessage(HttpMethod.Post, "https://accounts.spotify.com/api/token");
            var basic = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{clientId}:{clientSecret}"));
            req.Headers.Authorization = new AuthenticationHeaderValue("Basic", basic);
            req.Content = new FormUrlEncodedContent(new Dictionary<string, string>
            {
                ["grant_type"] = "client_credentials"
            });

            using var resp = await _http.SendAsync(req, cancellationToken);
            if (!resp.IsSuccessStatusCode) return null;

            var body = await resp.Content.ReadAsStringAsync(cancellationToken);
            using var doc = JsonDocument.Parse(body);
            _accessToken = doc.RootElement.GetProperty("access_token").GetString();
            var expiresIn = doc.RootElement.TryGetProperty("expires_in", out var e) ? e.GetInt32() : 3600;
            _tokenExpiry = DateTimeOffset.UtcNow.AddSeconds(expiresIn - 60);
            return _accessToken;
        }

        private static string Normalize(string? value)
        {
            if (string.IsNullOrWhiteSpace(value)) return "";
            var s = value.ToLowerInvariant();
            s = Regex.Replace(s, @"\s*[\(\[].*?[\)\]]", " ");   // drop (...) / [...]
            s = Regex.Replace(s, @"[^a-z0-9]+", " ");           // strip punctuation/diacritics-adjacent
            return s.Trim();
        }

        private static HashSet<string> Tokenize(string? value)
        {
            var norm = Normalize(value);
            return norm.Length == 0
                ? new HashSet<string>()
                : norm.Split(' ', StringSplitOptions.RemoveEmptyEntries).ToHashSet();
        }

        private static string? ExtractTrackId(string? spotifyUrl)
        {
            if (string.IsNullOrWhiteSpace(spotifyUrl)) return null;
            var m = Regex.Match(spotifyUrl, @"track[/:]([A-Za-z0-9]+)");
            return m.Success ? m.Groups[1].Value : null;
        }

        // ---- HTTP helper -----------------------------------------------------

        private async Task<string?> GetStringAsync(string url, CancellationToken cancellationToken)
        {
            try
            {
                using var resp = await _http.GetAsync(url, cancellationToken);
                if (resp.StatusCode == HttpStatusCode.TooManyRequests || !resp.IsSuccessStatusCode)
                    return null;
                return await resp.Content.ReadAsStringAsync(cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogDebug(ex, "GET failed: {Url}", url);
                return null;
            }
        }
    }
}
